CLASS zcl_plant_ger DEFINITION INHERITING FROM zcl_company_ger
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_plant_ger IMPLEMENTATION.
ENDCLASS.
