CLASS zcl_31_vat_ind_logali_ger DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  data vat_indicator TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_31_vat_ind_logali_ger IMPLEMENTATION.
ENDCLASS.
