CLASS zcl_padre_1_ger DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  CLASS-METHODS metodo1 RETURNING VALUE(rv_text) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS zcl_padre_1_ger IMPLEMENTATION.
  METHOD metodo1.
    rv_text = 'Método 1 de Clase Padre 1'.
  ENDMETHOD.

ENDCLASS.
